accessing
cuOOraCss
	"Este es el archivo css que se carga en el Index"

	^ 'body { background: darkcyan;}
		
	.error{
    color: darkred;
    font-weight: bold;
    padding: 4px;
    text-align: center;
    font-size: x-large;}

	.bordes{
		border-color:black}
	
	.user{
	    font-weight: bold;
    	margin-left: 120px;
	    font-size: x-large;
		position: absolute;
  		margin-top: 3px
}
	
.boton-inicio {
  position: fixed;
  padding: .375rem .75rem;
  border: 1px solid white;
  border-radius: .25rem;
  color: white;
  transition: color .15s ease-in-out,
    background-color .15s ease-in-out;
}

.boton-inicio:hover, .btn-borde:active, .btn-borde:focus {
  color: #fff;
  background-color: #007bff;
}
		
		.center{
		text-align:center;
		font-size:xx-large;
		font-style:oblique;}
		
		.boton{
    text-decoration: none;
    padding: 10px;
    font-weight: 600;
    font-size: 20px;
    color: #ffffff;
    background-color: #1883ba;
    border-radius: 6px;
    border: 2px solid #0016b0;
  }
  .boton:hover{
    color: #1883ba;
    background-color: #ffffff;
  }

.bg-1{

   background: linear-gradient(to right, rgb(97, 67, 133), rgb(81, 99, 149));
   height: 50vh;
   padding-top: 150px;
}
.t-stroke {
  color: transparent;
  -moz-text-stroke-width: 2px;
  -webkit-text-stroke-width: 2px;
  -moz-text-stroke-color: #000000;
  -webkit-text-stroke-color: black;
}
.t-shadow {
  text-shadow: 11px 13px 11px black;
}
	.form-registrer{
	font-size: large;
   font-weight: bold;
	text-align:center;
	font-style:oblique;}


	'