as yet unclassified
inicioComCss
^'
	.contador-dislikes{   
    margin-left: 25px;
    font-weight: bold;}

.contenedor-comments {
    margin-left: 5px;
    border: 3px solid #555;
    float: left;
    width: 84px;
    height: 40px;
    border-radius: 10px;}

.contenedor-dislikes{
	margin-left:5px;
    border: 3px solid #555;
	float:left;
    width: 60px;
    height: 40px;
    border-radius: 10px;}

.dislike{
        margin-left: 5px;
    font-weight: bold;
}
.like{
        margin-left: 11px;
    font-weight: bold;
}
	
	.boton-topico{
    text-decoration: none;
    padding: 10px;
    font-weight: 400;
    color: #ffffff;
    background-color: darkslategray;
    border-radius: 50px;
  }
  .boton-topico:hover{
    color: #1883ba;
    background-color: #ffffff;
  }


	.preguntaTitulo{
	font-size: xx-large;
    font-family: cursive;
	color:black;
	}
'