accessing
cuOOraCss
	"Este es el archivo css que se carga en el Index"

	^ 'body { background: #ffffff; font: 20 pt Arial, sans-serif;}

.title{
	font-size: 40pt;
	}	
				
.center{
	text-align:center;
	font-size:xx-large;
	}

.boton{
    text-decoration: none;
    padding: 10px;
    font-weight: 600;
    font-size: 20px;
    color: #ffffff;
    background-color: #0099ff;
  }

.boton:hover{
    color: #1883ba;
    background-color: #ffffff;
  }

.form-registrer{
	font-size: large;
   font-weight: bold;
	text-align:left;}
	'